static void addhistory(char *input);
static void addhistoryitem(struct item *item);
static void cleanhistory(void);
static void loadhistory(void);
static void navhistory(const Arg *arg);
static void searchnavhistory(const Arg *arg);
static void reallochistory(void);
static void restorebackupitems(void);
static void savehistory(void);
static void togglehistoryitems(void);
